# Generated by Django 4.1 on 2023-02-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_candles'),
    ]

    operations = [
        migrations.AddField(
            model_name='candles',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
